Repository rolling-scopes-school/tasks, pull requests merged in 2024-10, with the labels that each got.

#1712 feat: update self-intro examples
  stage1/modules/self-introduction/README.md
Labels: stage#1

#1706 docs: add a more detailed description
  tasks/css-meme-slider/README.md
Labels: stage#0

#1668 Stage0-Stage1 - update and fix Git & Markdown tasks description
  tasks/cv/cv-stage0.md
  tasks/cv/cv-stage1.md
  tasks/cv/cv.md
  tasks/cv/en/cv-stage0.md
  tasks/cv/en/cv-stage1.md
  tasks/cv/en/cv.md
  tasks/cv/en/git-markdown.md
  tasks/cv/git-markdown.md
  tasks/cv/images/find_deploy_01.png
  tasks/cv/images/find_deploy_02.png
Labels: stage#0

#1716 [2024Q4] Update Stage1 README & fix prettier warns
  devops/modules/3_ci-configuration/task_4.md
  stage1/README.md
  stage1/modules/js-fe-developer/README.md
  stage1/modules/rs-school-intro/README.md
  tasks/css-meme-slider/README.md
Labels: stage#1

#1713 [2024Q4] Christmas Shop
  tasks/christmas-shop/christmas-shop-part1.md
  tasks/christmas-shop/christmas-shop-part2.md
  tasks/christmas-shop/christmas-shop-part3.md
  tasks/christmas-shop/christmas-shop.md
  tasks/christmas-shop/gifts.json
  tasks/christmas-shop/img-compressed.zip
Labels: stage#1

#1718 fix: clarify html-css-git.md
  tasks/cv/en/html-css-git.md
Labels: stage#1

#1719 tasks' readme: update how often course starts
  README.md
Labels: enhancement

#1720 [2024Q4] Fix Christmas-shop Requirements
  tasks/christmas-shop/christmas-shop-part1.md
  tasks/christmas-shop/christmas-shop-part3.md
  tasks/christmas-shop/img-compressed.zip
Labels: stage#1
